import Foundation

enum DefaultVocabulary {
    static let cards: [Flashcard] = [
        Flashcard(term: "SOTA",
                  definition: "State of the Art — 現時点で最高性能の手法・モデル。",
                  example: "Our model achieves SOTA on ImageNet."),
        Flashcard(term: "Ablation Study",
                  definition: "各コンポーネントを取り除いて効果を検証する実験。",
                  example: "The ablation study confirms the attention module is critical."),
        Flashcard(term: "Baseline",
                  definition: "性能比較の基準となる既存手法やシンプルなモデル。",
                  example: "We compare against several strong baselines."),
        Flashcard(term: "Fine-tuning",
                  definition: "事前学習済みモデルを特定タスクに合わせて追加学習すること。",
                  example: "We fine-tune BERT on downstream tasks."),
        Flashcard(term: "Pre-training",
                  definition: "大規模データで汎用特徴を学習する事前学習フェーズ。",
                  example: "Pre-training on 1B tokens improves downstream performance."),
        Flashcard(term: "Zero-shot",
                  definition: "追加学習なしに未知タスクを解く能力。",
                  example: "GPT-4 shows impressive zero-shot reasoning."),
        Flashcard(term: "Few-shot",
                  definition: "少数の例示だけで新タスクを解く能力。",
                  example: "5-shot accuracy reaches 90% on this benchmark."),
        Flashcard(term: "Attention Mechanism",
                  definition: "入力のどの部分に注目するか動的に重み付けする機構。",
                  example: "Self-attention captures long-range dependencies."),
        Flashcard(term: "Transformer",
                  definition: "Attentionを主体とした深層学習アーキテクチャ。NLPの主流。",
                  example: "The Transformer revolutionized NLP."),
        Flashcard(term: "Epoch",
                  definition: "訓練データ全体を1回学習する単位。",
                  example: "Training for 100 epochs leads to convergence."),
        Flashcard(term: "Batch Size",
                  definition: "1回の勾配更新に使うサンプル数。",
                  example: "We use batch size 32 for stable training."),
        Flashcard(term: "Learning Rate",
                  definition: "パラメータ更新量を制御するハイパーパラメータ。",
                  example: "A learning rate of 1e-4 is used with Adam."),
        Flashcard(term: "Overfitting",
                  definition: "訓練データに過剰適合し汎化性能が低下する現象。",
                  example: "Dropout is applied to prevent overfitting."),
        Flashcard(term: "Regularization",
                  definition: "過学習を防ぐ制約・手法（L1, L2, Dropout など）。",
                  example: "L2 regularization is applied to all weights."),
        Flashcard(term: "Benchmark",
                  definition: "手法を比較評価するための標準化データセット・タスク。",
                  example: "We evaluate on the GLUE benchmark."),
        Flashcard(term: "Inference",
                  definition: "学習済みモデルで予測を行う推論フェーズ。",
                  example: "Real-time inference requires model optimization."),
        Flashcard(term: "Latent Space",
                  definition: "データ特徴を圧縮した低次元の潜在表現空間。",
                  example: "Similar images cluster in the latent space."),
        Flashcard(term: "Embedding",
                  definition: "離散データを連続ベクトル空間に写像する表現。",
                  example: "Word embeddings capture semantic similarity."),
        Flashcard(term: "Cross-entropy Loss",
                  definition: "分類タスクの損失関数。予測確率と正解の差を測る。",
                  example: "We minimize cross-entropy loss during training."),
        Flashcard(term: "F1 Score",
                  definition: "Precision と Recall の調和平均。不均衡データの評価指標。",
                  example: "The model achieves F1 = 0.94 on the test set."),
        Flashcard(term: "Knowledge Distillation",
                  definition: "大きな教師モデルの知識を小さな生徒モデルへ転移する手法。",
                  example: "Distillation reduces model size with minimal accuracy loss."),
        Flashcard(term: "Contrastive Learning",
                  definition: "類似サンプルを近づけ非類似サンプルを遠ざける自己教師学習。",
                  example: "SimCLR uses contrastive learning for visual representations."),
        Flashcard(term: "Generalization",
                  definition: "未知データへの適応能力。汎化性能。",
                  example: "Data augmentation improves generalization."),
        Flashcard(term: "Convergence",
                  definition: "学習が安定し損失が最小値に近づく状態。",
                  example: "Loss convergence is observed after 50 epochs."),
        Flashcard(term: "Hyperparameter",
                  definition: "学習前に設定するパラメータ（学習率・バッチサイズなど）。",
                  example: "Hyperparameter tuning is done via grid search."),
    ]
}
